"""Create a test shame post for Instagram testing."""

from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

def create_test_post():
    """Create a test shame post."""

    # Create output directory
    output_dir = Path("data/posts")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Create image (Instagram square: 1080x1080)
    img = Image.new('RGB', (1080, 1080), color=(45, 52, 54))  # Dark background
    draw = ImageDraw.Draw(img)

    # Try to load fonts
    try:
        huge_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 100)
        big_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 80)
        medium_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 50)
        small_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 35)
    except:
        huge_font = ImageFont.load_default()
        big_font = ImageFont.load_default()
        medium_font = ImageFont.load_default()
        small_font = ImageFont.load_default()

    # === TOP RED BANNER ===
    draw.rectangle([0, 0, 1080, 180], fill=(231, 76, 60))

    # Title
    title = "📱 PHONE SHAMER TEST 📱"
    bbox = draw.textbbox((0, 0), title, font=big_font)
    title_width = bbox[2] - bbox[0]
    draw.text(((1080 - title_width) // 2, 50), title, fill=(255, 255, 255), font=big_font)

    # === CENTER CONTENT ===
    # Big number
    number = "7"
    bbox = draw.textbbox((0, 0), number, font=huge_font)
    num_width = bbox[2] - bbox[0]

    # Circle behind number
    circle_center = (540, 450)
    circle_radius = 200
    draw.ellipse(
        [circle_center[0] - circle_radius, circle_center[1] - circle_radius,
         circle_center[0] + circle_radius, circle_center[1] + circle_radius],
        fill=(52, 152, 219)  # Blue circle
    )

    draw.text(((1080 - num_width) // 2, 390), number, fill=(255, 255, 255), font=huge_font)

    # Text below number
    caught_text = "TIMES CAUGHT TODAY!"
    bbox = draw.textbbox((0, 0), caught_text, font=medium_font)
    text_width = bbox[2] - bbox[0]
    draw.text(((1080 - text_width) // 2, 540), caught_text, fill=(255, 255, 255), font=medium_font)

    # === MIDDLE STATS ===
    stats_y = 700

    stats = [
        "📅 Testing Mode - Not Real Data",
        "📊 This is a sample post",
        "✅ Use for Instagram testing"
    ]

    for i, stat in enumerate(stats):
        bbox = draw.textbbox((0, 0), stat, font=small_font)
        text_width = bbox[2] - bbox[0]
        draw.text(((1080 - text_width) // 2, stats_y + i * 50), stat,
                 fill=(178, 190, 195), font=small_font)

    # === BOTTOM MESSAGE ===
    caption = "This is a TEST post for Instagram integration!"
    bbox = draw.textbbox((0, 0), caption, font=medium_font)
    caption_width = bbox[2] - bbox[0]
    draw.text(((1080 - caption_width) // 2, 950), caption, fill=(255, 255, 255), font=medium_font)

    # === WATERMARK ===
    watermark = "Generated by Phone Shamer"
    bbox = draw.textbbox((0, 0), watermark, font=small_font)
    watermark_width = bbox[2] - bbox[0]
    draw.text(((1080 - watermark_width) // 2, 1030), watermark,
             fill=(99, 110, 114), font=small_font)

    # Save
    output_path = output_dir / "TEST_shame_post.png"
    img.save(output_path, quality=95)

    print(f"✅ Test image created: {output_path}")
    print(f"📐 Size: 1080x1080 (Instagram ready)")
    print(f"\n📱 Test it with:")
    print(f"   python3 post_to_instagram.py --image {output_path} --type story")
    print(f"\n💡 This is safe test data - won't reveal real phone usage!")

    return str(output_path)


if __name__ == "__main__":
    create_test_post()
